name: Apply Infrastructure
run-name: Apply ${{ inputs.environment }} Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "Environment to deploy to"
        default: "dev"
      runs_on:
        type: string
        description: The runner group label to use for the actions
        default: "arc-runner-set"
      working_directory:
        type: string
        description: "The directory where infrastructure code resides"
        default: "./"
      aws_region:
        type: string
        description: "If using AWS, the region to target. Defaults to us-east-1."
        default: "us-east-1"
      use_oidc:
        type: string
        description: "Use the OIDC provider to authenticate the provisioning process"
        default: "false"
      environments_config_dir:
        type: string
        description: "Provide environment folder path"
        default: "./environments"
      tf_log:
        type: string
        description: The log level you want terraform to run with
        default: "ERROR"
    secrets:
      JB_ACTIONS_PRIVATE_KEY:
        required: true
      AWS_ASSUME_ROLE:
        required: true
      AWS_ACCOUNT_NUMBER:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: OpenTofu apply
    runs-on: ${{ inputs.runs_on }}
    environment: ${{ inputs.environment }}
    env:
      TF_VAR_role_name: ${{ secrets.AWS_ASSUME_ROLE }}
      TF_VAR_account_number: ${{ secrets.AWS_ACCOUNT_NUMBER }}
      TF_VAR_deployment_region: ${{ inputs.aws_region }}
      TF_LOG: ${{ inputs.tf_log }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install missing dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip git

      - name: Generate token
        uses: actions/create-github-app-token@v1
        id: generate_token
        with:
          app-id: 965107
          private-key: ${{ secrets.JB_ACTIONS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: configure git
        run: git config --global url.https://oauth2:$GH_TOKEN@github.com.insteadOf ssh://git@github.com
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Log in to AWS using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ inputs.use_oidc == 'true' }}
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/${{ secrets.AWS_ASSUME_ROLE }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: OpenTofu Init
        id: init
        run: tofu init -input=false -backend-config=${{ inputs.environments_config_dir }}/${{ inputs.environment }}/backend.hcl

      - name: Download the plan
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.aws_region }}-tf-plan
          path: ${{ inputs.working_directory }}

      - name: Apply the plan
        id: apply
        run: tofu apply -input=false -no-color -auto-approve out_${{ inputs.aws_region }}.tfplan

      - name: Create the apply summary
        uses: actions/github-script@v7
        if: always()
        id: summary
        continue-on-error: true
        env:
          APPLY: "${{ steps.apply.outputs.stdout }}"
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            // 1. Prep the output
            const output = `#### OpenTofu Apply 🚗\`${{ steps.apply.outcome }}\`

            <details><summary>Show details</summary>

            \`\`\`\n
            ${process.env.APPLY}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ inputs.working_directory }}\`, Workflow: \`${{ github.workflow }}\`*`;

            // 2. Set the output variable
            const fs = require('fs');
            fs.writeFileSync('${{ inputs.working_directory }}/summary.md', output);
            core.setOutput('summary', output);

      - name: Write the step summary
        if: always()
        continue-on-error: true
        run: cat summary.md >> $GITHUB_STEP_SUMMARY